### ISSUE TITLE
Arranging files with paired end short-reads

### ISSUE THREAD

**Issue by andreaswallberg** [vpc-ccg/haslr#3]
Dear developers,

This looks like a great tool!

With regards to Forward/Reversed PE reads:

Can the F/R reads be provided one after another in the same fastq file or do they have to be provided as two separate files?

Similarly, can the program read more two or more pairs of F/R files?

**Comment by haghshenas** [comment]
Hi @andreaswallberg 
Thanks for your interest in our tool.
Since HASLR uses Minia for short read assembly, paired-end information will be ignored. This means that Minia treats all short reads as single-end. So it really doesn't matter if they are in a single file or two separate files.

Yes, you can pass many short read files.

**Comment by haghshenas** [comment]
Just pass all short read files after `-s` (separated by space).
